### PR TITLE
updated jtds to 1.3.0 and h2 to 1.3.169

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
Jtds is also used for QoQ as second chance, so we have to Test QoQ as well.

**Comment by igal-getrailo** [comment]
Are there specific tests that you want to run?

I deployed this on a production server that has a live app with MSSQL and
some QoQs.   It's been running fine for over 48 hours now.

## 

typos, misspels, and other weird words brought to you courtesy of my mobile
device.

**Comment by micstriit** [comment]
i will run it through all my testcases (we have to publish this testcases
asap, i know).

Micha

2012/11/26 Igal notifications@github.com

> Are there specific tests that you want to run?
> 
> I deployed this on a production server that has a live app with MSSQL and
> some QoQs. It's been running fine for over 48 hours now.
> 
> ## 
> 
> typos, misspels, and other weird words brought to you courtesy of my
> mobile
> device.
> On Nov 25, 2012 11:29 PM, "Michael Offner" notifications@github.com
> wrote:
> 
> > Jtds is also used for QoQ as second chance, so we have to Test QoQ as
> > well.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/getrailo/railo/pull/87#issuecomment-10706796>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/getrailo/railo/pull/87#issuecomment-10707009.

## 

/micha

Michael Offner CTO Railo Technologies GmbH

**Comment by igal-getrailo** [comment]
I get an error now in a very specific case of a STORED PROCEDURE that includes a call to a UDF (that's MSSQL UDF, not Railo).

jTDS1.2.5 was working fine.  I will try to use jTDS1.2.7 and see if this problem goes away.

my current conclusion is that jTDS1.3.0 is not a good upgrade though.

**Pull request closed without merging**
