### PR TITLE
https://issues.jboss.org/browse/RAILO-2625

### PR DESCRIPTION
**Pull request by clitnak**
Allows the ability to have member functions on functions themselves.
https://issues.jboss.org/browse/RAILO-2625

### CODE REVIEW

**Comment by micstriit** [comment]
we have adapted your implementation
https://github.com/getrailo/railo/commit/5c9fd66911ff43e1c239878b25fb66f1b88f98af

but we could not use it one to one, because we had a lot of changes with this implementation the last 24 hours.
we also use a DatasourceException instead of a SQLException

**Comment by micstriit** [comment]
FYI CommonUtil.toPageException() is newly used in the complete hibernate implementation instead of Caster.toPageException(), so we cover a lot more with this implementation.

**Comment by clitnak** [comment]
I think your comments were for a different pull. I would like this pull to be re-opened, if possible please.

**Comment by micstriit** [comment]
duplicate pull

**Pull request closed without merging**
