### PR TITLE
cffunction localmode added to admin doc

### PR DESCRIPTION
**Pull request by brucekirkpatrick**
Added the missing localmode attribute documentation for cffunction in railo admin.

### CODE REVIEW

**Comment by micstriit** [comment]
That's great, but we have to be a little bit careful with that, the tld is not only a documentation, the main purpose of this file is to define the rules of a tag for the compiler. Having a doc is only a nice addition.
At the moment localmode is handled at runtime we have to check what impact this can have

**Comment by brucekirkpatrick** [comment]
I noticed that localization has been created for scope and other admin pages, but functions and tags are currently not able to be translated.   Perhaps a future version of Railo will consider that admin documentation and runtime definitions should be separate not only to be more complete, but to allow translation.  I really didn't know this feature existed until 3 days ago.

**Comment by brucekirkpatrick** [comment]
Maybe you can also add an xml child node to each attribute to mark whether it is runtime or fixed instead of defining this at the function/tag level.  I assume the code to process the xml could be upgraded with just a little logic to achieve that.

**Comment by micstriit** [comment]
we work for a while on a online app, that allows to maintain this file, including other languages, other languages will be referenced in other files, but this is on hold for the moment.

**Pull request merged**
