### PR TITLE
added admin driver for H2 database in Server Mode

### PR DESCRIPTION
**Pull request by isapir**
hopefully this is an easier way to add the file for https://issues.jboss.org/browse/RAILO-2006 

-- I'm still trying to figure out the "best" process for contributing code/text changes so if I'm doing it wrong please let me know.

Igal

### CODE REVIEW

**Comment by micstriit** [comment]
where is the difference to the H2.cfc?

**Comment by isapir** [comment]
it's got very different settings so I created a new file.  

it is not supposed to replace the current H2.cfc but to be added in addition to it.

it connects to an H2 server that listens on a TCP port (default is 9092 and there's no need to specify it)

**Comment by micstriit** [comment]
sorry but i cannot see a difference in the file just 2 replaced operators "not" -> ! and "and" -> && and some addional comments

**Comment by isapir** [comment]
yea, sorry about that.  after I read your message and looked at the file I realized that I made a mistake with that file and I replied to the group with the correct code.

the correct code is also available at https://issues.jboss.org/browse/RAILO-2006 as attachment.

**Comment by isapir** [comment]
wrong file.  sorry.

**Comment by micstriit** [comment]
np

## 

Michael Offner
Gesendet mit Sparrow (http://www.sparrowmailapp.com/?sig)

Am Freitag, 14. September 2012 um 10:58 schrieb dev-21solutions:

**Pull request closed without merging**
