### PR TITLE
added .cfs extension for processing cfscript without tag

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
perhaps i miss something, but why should the first parser approach fail, when i have for example "Hello World" in the  .cfs template? What is the exception in that case?

This is only halfway done, for example should the method getCFMLExtensions include this new extension?
if so does it makes sense in every place?
Did you review every place where "getCFMLExtensions" and "getCFCExtension" is used. has this change a impact on all this.
What about the setting in admin about custom tags extensions?
with Railo 2.0 we had extensions definition spread all over Railo, with 3 i have moved that in a central place, because of that i know that a change like this has a huge impact on the system and it needs more adjustment for sure

**Comment by igal-getrailo** [comment]
1) I'm not sure what you mean.  when you have in the .cfs "Hello World" it does NOT fail and there is No exception.  it is exactly as if you wrote:

```
<cfscript>"Hello World"</cfscript>
```

if instead, you have it without the quotes, e.g.:

```
<cfscript>Hello World</cfscript>
```

then it fails in both cases (cfscript and .cfs) with the same exception

```
Missing [;] or [line feed] after expression 
at railo.transformer.cfml.script.AbstrCFMLScriptTransformer.checkSemiColonLineFeed(AbstrCFMLScriptTransformer.java:1569)
```

2) CFCs should Not be written with the .cfs extension just like they shouldn't be written with the .cfm extension, so getCFCExtension should not be modified for this.

3) I on purpose did not touch getCFMLExtensions for now as I am not sure of the implications and wanted to discuss that with you, but I disagree that this is halfway done -- IMO it is fully functional and working properly, and if we want to add the option to add that extension for Custom Tags etc., then it would be easy to add from here.

I know from experience that if I will implement the whole thing and submit a huge Pull request then it will take you much longer to review and accept it, so I bring it to the point where it is functional and we can always improve on it, as we can improve on much of the code in the project.

the more time that passes from the Pull request until you get to review it, the bigger the chance that some of the files would change and the Pull will not merge smoothly, and then much of the work needs to be redone.

**Comment by micstriit** [comment]
1) on line 152 in CFMLTransformer
152: if(p.isPage() && (ext.equalsIgnoreCase(config.getCFCExtension()) || isCFS) ) {

this "if(p.isPage()..." check if the Page (p) is not a Interface or a component and only in that case it recompiles the code.  
what is right for cfcs, then when i have a page, i know railo was not able to compile to a component/interface, but now you used  it for .cfs what is not a component/interface, so "isPage" always return true and you compile the template ALWAYS twice. that rules simply not apply for .cfs

**Comment by micstriit** [comment]
2) could not agree more!

**Comment by micstriit** [comment]
3) it is needed for custom tags, looking for index.cfs?, compiled file name? application.cfs/onRequestStop.cfs search? ... they are really many places the extensions matter.

**Comment by igal-getrailo** [comment]
please see #341 instead

**Pull request closed without merging**
