### PR TITLE
Update railo-cfml/railo-internal-cfml-tags/Dump.cfc

### PR DESCRIPTION
**Pull request by sneiland**
Added the ability to collapse individual rows.

### CODE REVIEW

**Comment by igal-getrailo** [comment]
@sneiland - thank you for your input.  a few comments/questions though:

1) we never add new functionality to the master branch as it has the potential of introducing bugs to production deployments.  new functionality should go into the Develop branch only.  also, some changes have been made already Dump.cfc in the other, more up to date, branches, so your changes may or may not clash with other changes.

2) you added a "supported format" of "updated" in line 10.  supported formats are used in other places of the code and unless we add them there this will never be called.  further, if the format "updated" will manage to be passed, an exception will be thrown at line 92 as there will be an attempt to call a method named updated, i.e. this.updated( ... ) and you did not provide such a method.  not sure why you added it?  did you test it?  I doubt that it would work with no error.

3) this is the wrong file to update for Dump.cfc (I know it's confusing...  we're working on cleaning it up).  the correct file is https://github.com/getrailo/railo/blob/develop/railo-java/railo-core/src/resource/library/tag/Dump.cfc

4) that file was written long ago and has many issues with it.  one example of a performance issue is the extensive, unnecessary, string concatenation.  another is the old use of js with global functions (dumpOC) which can clash with user code. 

I am working on cleaning this up but we're always open to input from users, so thanks again.

**Comment by sneiland** [comment]
The "updated" format was simply a hold over from when I was pulling apart the code to try work out how to update it. It should not have been in there.

I will use the correct file you mentioned and rework it to incorporate my update. Thanks for clearing that up.

p.s. Is there a page documenting this, best practices for which branch to use etc that I missed.

**Comment by igal-getrailo** [comment]
I'm not sure if there's a page in the wiki yet, but we should add it if not.

as for you changes -- I plan on overhauling this template with updated js, css, etc.  is there anything in particular that you want to add?

**Comment by sneiland** [comment]
I added a couple of thing. I added a css rule to give the clickable cells a pointer cursor. I also modified the structure to make the rows collapsible like in acf.

Also Im not sure how relevent but the code I started out with was the actual Dump.cfc file in my local install of railo 4. I did not start from the github code. (Which I probably should have done).

**Comment by igal-getrailo** [comment]
actually I think that I already added the pointer cursor to the develop branch.  I will modify the JS code and the CSS.  the "collapsibillity" of things is one of the goals so that will be taken care of.

very relevant -- you should definitely start with the git code (develop branch) in this case.  that file is already modified from the one released with Railo4 so merging your changes will be messy if you start from an older version.

**Pull request closed without merging**
