### PR TITLE
Feature/query cfc

### PR DESCRIPTION
**Pull request by Zoramite**
Fixing a bug that was not keeping the rest of the string after the last query param.

### CODE REVIEW

**Comment by andreacfm** [comment]
Hi,
may you please provide a small test case that we can run?

**Comment by Zoramite** [comment]
Sure! I was running a query similar to this:

https://gist.github.com/886897

The sql that was being generated was cutting off the last `)` so the query was failing.

**Comment by andreacfm** [comment]
Thanks.
I will review asap.

Thanks for contribution.

Andrea

**Comment by andreacfm** [comment]
Thanks.
I have pushed from my fork into railo core.

**Comment by shermes641** [comment]
This still is a problem on Railo 3.3.0.027
JIRA   RAILO-1496     https://issues.jboss.org/browse/RAILO-1496

**Comment by Zoramite** [comment]
From what I can tell, the railo upgrade process does not replace those files in your WEB-INF folder. So I would try copying the latest version of the Query.cfc and see if it works correctly.

**Comment by shermes641** [comment]
Okay, thanks.

**Pull request closed without merging**
