### PR TITLE
solves ticket railo-2147

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
testcase fails in my environment, all queries returned are empty. i have also attached a modified testcase to the ticket, it works the same way as your testcase but is based on the railo testcase template and is following this rules

**Comment by igal-getrailo** [comment]
What db are you using?  I tested it on MySQL and compared the results with
ACF 10.

Did you change the flag to create the db tables?

## 

typos, misspels, and other weird words brought to you courtesy of my mobile
device and its auto-(in)correct feature.

**Comment by micstriit** [comment]
5.5.28

i have changed the creation of the tables in my testcase (see attachment in ticket), railo checks for existence (with a "select \* from ...") and if they not exist, railo creates them, a testcase should always work out of the box, and should not need additional steps. i have also renamed the tables, the ticket number should always be part of the table name

**Comment by igal-getrailo** [comment]
I used your testcase and it works fine for me (the only thing I modified 
was the DSN to match my local settings.).

see attached screenshot.

Igal

**Comment by igal-getrailo** [comment]
p.s. -- I'm using MySQL 5.5.29 Winx64 so it should be the same as your 5.5.28

**Pull request merged**
