### PR TITLE
solved ticket https://issues.jboss.org/browse/RAILO-2250

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
Does this work for you, I mean when you call stringIsEmpty("");
I'm sure you will a exception with this.

**Comment by micstriit** [comment]
The member function works because the member function is using the bif interface, but the code is risky because the fld does not match the implementation.

**Comment by igal-getrailo** [comment]
you're right.  I will add a new function altogether.

**Comment by igal-getrailo** [comment]
please see updated code

**Pull request merged**
