### PR TITLE
renamed Empty to IsEmpty

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
i have changed it a little bit
https://github.com/getrailo/railo/commit/8b258f1a871c4715e64277337e90b0757b1e1daa
open for discussion, specially the functionality

**Comment by igal-getrailo** [comment]
I didn't test it but it looks like it will not handle arrays and struct properly.  

I prefer functionality more like Gert's example at http://blog.getrailo.com/post.cfm/isempty-function -- which is what triggered the conversation about the is empty BIF in the forum.

**Comment by micstriit** [comment]
Why you think this?!

this are the testcases for struct and array (attached in the ticket)



<cf_valueEquals left="#isEmpty([])#" right="#true#">
<cf_valueEquals left="#isEmpty([1])#" right="#false#">



<cf_valueEquals left="#isEmpty({})#" right="#true#">
<cf_valueEquals left="#isEmpty({a:1})#" right="#false#">

MIcha

2013/1/14 Igal notifications@github.com

> I didn't test it but it looks like it will not handle arrays and struct
> properly.
> 
> I prefer functionality more like Gert's example at
> http://blog.getrailo.com/post.cfm/isempty-function -- which is what
> triggered the conversation about the is empty BIF in the forum.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/getrailo/railo/pull/109#issuecomment-12231612.

## 

/micha

Michael Offner CTO Railo Technologies GmbH

**Comment by igal-getrailo** [comment]
good point.  that's why I wrote "I didn't test this...".  I will speak more (if at all) after I test it ;)

**Pull request closed without merging**
