### PR TITLE
Added the option for uploading Railo Extensions in the admin

### PR DESCRIPTION
**Pull request by paulklinkenberg**
As the title says, I Added the option for uploading Railo Extensions in the admin.
I also cleaned up the code of the extensions module, with correct indentation, and some styling changes.

### CODE REVIEW

**Comment by cybersonic** [comment]
Wow, old but can you reference the JIRA ticket for this request please?

**Comment by paulklinkenberg** [comment]
Thanks Mark, I created a ticket now: https://issues.jboss.org/browse/RAILO-2079
Since this was a special request by Gert, I just mailed Micha and Gert about this back then.

**Comment by paulklinkenberg** [comment]
These changes are also included in the new pull request https://github.com/getrailo/railo/pull/59

**Comment by paulklinkenberg** [comment]
These changes are pulled meanwhile; closing pull req

**Pull request closed without merging**
