### PR TITLE
[JBoss JIRA] (RAILO-112​0) IE 8 Security / Access page blank

### PR DESCRIPTION
**Pull request by vkras**
.../browse/RAILO-1120

### CODE REVIEW

**Comment by vkras** [comment]
Fix for "RAILO-554 Multi-select of datasources in admin fails in IE8" in addition to [JBoss JIRA](RAILO-112​0) IE 8 Security / Access page blank

**Comment by micstriit** [comment]
i have seen to late that the pull request was made again the master branch and should be again the "3.3" branch, we will add this changes to "3.3" branch as well.

**Comment by micstriit** [comment]
changes in branch "3.3"
https://github.com/getrailo/railo/commit/44d6858534afaf5fada5c2c65a297a7bfc075e0d

**Comment by vkras** [comment]
I just installed the latest 3.3.1.009.
RAILO-1120 IE 8 Security / Access page blank - can be set to Resolved, it works fine.

Something happened during merge for the RAILO-554  Multi-select of datasources in admin fails in IE8 (https://github.com/vkras/railo/commit/6adcc36dc3f1f9c31a9e169e74c5f346aab3efe2).
If my changes, fix looked like this:
if(form.elements[key] && (""+form.elements[key].name).indexOf("row_")==0){

The version I installed, looks like this (please note location of brackets):
if((form.elements[key] && ""+form.elements[key].name).indexOf("row_")==0){

It's wrong, it throws JS error in IE.

**Pull request merged**
