### PR TITLE
outputs msg like: ERROR: variable [XYZ] doesn't exist

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
i disagree with this change, the following 2 lines should be having the same affect
dump(notExisting);
dump(eval="notExisting");

but with this change, the second line no longer throws a message, it just outputs the error message.

**Comment by igal-getrailo** [comment]
but eval gives us a chance to do a graceful output instead of throwing an error.

you actually supported it in the JIRA comment:
https://issues.jboss.org/browse/RAILO-1906?focusedCommentId=12738808&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12738808

if var="#notExisting#" and eval="notExisting" are exactly the same then what's the benefit of eval?  just a shortcut for the #hash# signs and the label?  

seems to me like we're missing out on an added value for eval, which is not available with the var counterpart if null support is disabled.

**Comment by micstriit** [comment]
sorry, i have forget about that one, but i have written in my comment
"I'm not really sure if I prefer the current behavior."
in that case i think i prefer consistence and the current behavior.

yes i have invented "eval" as shortcut for #hash# signs and the label

if we do so, we should not only do for eval, we can also do for this
var="#notExisting#"
but if we do, we should not simply outputs this the same way as a string, it should looks different, for example still the error template colors and more information.

**Comment by igal-getrailo** [comment]
OK, I saw that you wrote "I'm not really sure if I prefer the current behavior.".  The current behavior throws an exception so I thought that you agree with me there.

I agree that it will be better if the error is marked as Error and not String.  But how can we support this for var=#notExisting# if null support is disabled?  The error will occur before we even get to the dump.

That's what's nice about eval.

**Comment by micstriit** [comment]
this has nothing to do with null support enabled/disabled, we can do it the
same way, we do the same with isNull or parameterexists.
it needs some work to support this with cfml based tags/functions but it is
possible

Micha

2013/1/7 Igal notifications@github.com

> OK, I saw that you wrote "I'm not really sure if I prefer the current
> behavior.". The current behavior throws an exception so I thought that you
> agree with me there.
> 
> I agree that it will be better if the error is marked as Error and not
> String. But how can we support this for var=#notExisting# if null support
> is disabled? The error will occur before we even get to the dump.
> 
> That's what's nice about eval.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/getrailo/railo/pull/105#issuecomment-11961822.

## 

/micha

Michael Offner CTO Railo Technologies GmbH

**Pull request closed without merging**
