### PR TITLE
Feature/railo 2496

### PR DESCRIPTION
**Pull request by cybersonic**

### CODE REVIEW

**Comment by cybersonic** [comment]
This has been merged outside of github (since it couldn't' be merged automatically)

**Comment by igal-getrailo** [comment]
"(since it couldn't' be merged automatically)" -- you merged it into Master, probably without updating your local Master first with a Pull.

we usually push into 4.0/4.1/Develop and merge Master from that.

**Comment by cybersonic** [comment]
I merged it into develop I hope!

Regards
Mark Drew

**Comment by igal-getrailo** [comment]
Possibly, but the pull request here showed Master:
   cybersonic wants to merge 367 commits into getrailo:master  from cybersonic:feature/RAILO-2496
So perhaps that was the reason it didn't let you do it smoothly.

**Comment by cybersonic** [comment]
Good point! Although I am sure I changed that! Well spotted and boo to the GitHub interface. 

Regards
Mark Drew

**Pull request closed without merging**
