### PR TITLE
updated mysql driver from 5.0.8 to 5.1.25

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
i have changed the versions file as well
https://github.com/getrailo/railo/commit/6fbf9bc7519f59b49c06f61f1cee5e2f8c209f07

**Comment by lmajano** [comment]
I recommend reverting to 5.1.20 as these versions of the JDBC drivers have a bug with MySQL deadlocks when using timestamps.  The only version that does not have this issue is 5.1.20.  These drivers under load can bring a site down.

**Comment by lmajano** [comment]
Reference for you guys
http://bugs.mysql.com/bug.php?id=67760

**Comment by igal-getrailo** [comment]
@lmajano - the bug is reported on 5.1.22;  is there a reason you recommend 5.1.20 and not 5.1.21 for example?

**Comment by lmajano** [comment]
Because of the comments by the developer:
Verified as described. Problem is not repeatable with version 5.1.20

**Comment by igal-getrailo** [comment]
ok, cool.  I'm surprised they haven't fixed it yet since it seems like a major issue.

are you currently using 5.1.20?  looks like we should downgrade as you suggested.

**Comment by lmajano** [comment]
yes, I am very surprised that is open for so long. They offer a workaround on adding some properties to it.  Actually can you do this in Railo via the admin?

I actually started with the one that Railo ships and had deadlocks, moved to the latest and deadlocks continued.  Downgraded to 5.1.20 and my deadlocks disappeared.

**Comment by igal-getrailo** [comment]
"I actually started with the one that Railo ships" -- which one?  5.0.8?  5.1.25?  5.1.25 was the latest when I downloaded it a couple of weeks ago.

do you have the link for downloading 5.1.20 from mysql?  I can find it on maven-repo but not in the mysql website.

**Comment by igal-getrailo** [comment]
see https://github.com/getrailo/railo/pull/234

**Pull request merged**
