### PR TITLE
Railo 2162 + 2163

### PR DESCRIPTION
**Pull request by igal-getrailo**
solves both tickets 2162 and 2163

if accepted, you can close pull request 81

### CODE REVIEW

**Comment by micstriit** [comment]
there is already a action to get the running threads, of course we can extend this functionality, but adding a new action makes no sense.
<cfadmin action="surveillance" type="server"
        password="server" returnvariable="allThreads">

**Comment by micstriit** [comment]
please to not a pull request addressing more than one ticket, like in this case, this can give us troubles, because we have to reject the work done for 2163, but not for 2162

**Comment by micstriit** [comment]
please try not to spread System.properties over the core, we try to capsule system properties in the class SystemUtil.
so for the line seperator for example, there is a method called "getOSSpecificLineSeparator()".

**Comment by micstriit** [comment]
i have added the StringBuffer replacement, a little bit modified
https://github.com/getrailo/railo/commit/486b347635b0a1f23434d5c488644e70cbeb3012

**Comment by micstriit** [comment]
we also have to be extremely careful using classes from package
com.sun.*, this classes are not guaranteed in any JRE. only use them in independent classes, so if this class break the rest still is working, having this as import in railo.runtime.tag.Admin, means if the environment does not have it, the complete admin fails.

**Comment by igal-getrailo** [comment]
good catch on using multiple append() calls instead of string 
concatenation via + operator :)

**Comment by igal-getrailo** [comment]
I'm still trying to learn where these "global" methdos are ;)

**Comment by igal-getrailo** [comment]
but that's exactly how I separated them.

Pull #81 was for ticket #2162 and Pull #82 was for both.  so if you had 
rejected Pull #82 and accepted #81 you would have gotten exactly that.  
(the StringBuilder was something I thought of afterwards).

I did it this was because both tickets changed the same file which would 
have required you to do a file-level merge.

**Pull request closed without merging**
