### PR TITLE
Adding the ESAPI encodeFor<X> functions

### PR DESCRIPTION
**Pull request by cybersonic**
I have added the ESAPI library, so that we can also implement the encodeFor<x> functions

### CODE REVIEW

**Comment by micstriit** [comment]
there should be a prefix in the function names and it would make sense to have only 2 function instead of so many:
encodeForCSS --> esapiEncode("css",...)

**Comment by micstriit** [comment]
the jar name should not contain a version number, this makes update for client more complicated. when client just copy new jar files in lib folder and the jars have version number, the client end with multiple versions of the same jar. we had this problem in the begining, because of that the jars always have removed the version number from name and the original name is in file "version"

**Comment by micstriit** [comment]
why "Whole bunch of text fixes" remove "customError" trigger frm cfform?

**Comment by micstriit** [comment]
"adding the CLI to the build process" why is railo-cli.jar part of the repository, this should be only as source in repository

**Comment by micstriit** [comment]
"adding the webroot" for what this is good for?

**Comment by micstriit** [comment]
"fixing missing libs" has version number in jar file

**Comment by cybersonic** [comment]
I have added these issues to my repo's tickets:
https://github.com/cybersonic/railo/issues

**Comment by cybersonic** [comment]
also this pull request seems to have brought in a lot of stuff from the build process too. Hence the "web root and adding CLI" Which I guess shouldn't be part of this pull request but since my source has moved on, the pull would be for my whole branch.

**Pull request merged**
