### PR TITLE
Jira 2384b

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
the complete null handling in the query object is very complicated and fragile, you cannot simple change it that way, this will break a lot of other code!

**Comment by micstriit** [comment]
with this change you indicate that null is equal to not existing, but this is not always the case (even with full null support disabled), only some functioniality in the code assumes this behaviour, like i have written before it is a lot more complicated and this change would break a lot of code!

**Comment by micstriit** [comment]
btw: i plan to do exact the opposite in the future, we have code like this in the get method that throws a exception, i plan to remove that code in the future, but this is not that easy, because a lot of code is depending on the current behaviour

**Comment by micstriit** [comment]
initial problem was the changes we did for ticket 2545, i have solved the issue, see details in this ticket

**Comment by igal-getrailo** [comment]
which change can break existing code?  the one is UndefinedImpl.java?

the other changes only affect the Query iterator, and that has always in CFML traslated NULL as Empty-String until now, so it is very un-intuitive for CFML developers to check for null values in a Query.

**Comment by igal-getrailo** [comment]
how about moving the column-names outside the function as in
https://github.com/getrailo/railo/pull/232/files#L1R18
?

getColumnNames() creates a defensive copy so calling it each time inside the iterator just slows things down

**Comment by micstriit** [comment]
yes, i have seen that part and make this change, i just not have pushed it
https://github.com/getrailo/railo/commit/c800c904386e74281f676f96d2c3c2a16d957a9d

Micha

2013/8/6 Igal notifications@github.com

> how about moving the column-names outside the function as in
> https://github.com/getrailo/railo/pull/232/files#L1R18
> ?
> 
> getColumnNames() creates a defensive copy so calling it each time inside
> the iterator just slows things down
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/getrailo/railo/pull/232#issuecomment-22204916
> .

## 

/micha

Michael Offner CTO Railo Technologies GmbH

**Pull request closed without merging**
