### PR TITLE
added alias of region to cacheName arguments in cache BIFs.

### PR DESCRIPTION
**Pull request by igal-getrailo**
also added alias of CacheRemoveAll() for CacheClear()
and CacheIdExists() for CacheKeyExists()

### CODE REVIEW

**Comment by micstriit** [comment]
sorry i have already done the same, but a little bit more, i have not only added "region" as alias, i have also added "cache", then i have also added aliases for the id argument ("name" and "key")

**Comment by micstriit** [comment]
https://github.com/getrailo/railo/commit/e9ef1f75f76140f86b2d2b51729e2a7c5747d4c3

**Comment by igal-getrailo** [comment]
Are you sure that you want to add alias "name" for ID?  It can be confusing with cacheName which refers to the cache connection name.

**Comment by micstriit** [comment]
this alias ar nowhere visible
they are really just for named argument calls and not documeted (a hidden
feature for compatibility to acf and avoid ugly un unlogical names from ACF)
so if you write
cacheget(name:"susi");
it will work.

for me the name "name" make sense, because the second argument of cachePut
is called "value"
cachePut(name:"susi",value:'Susanne');

"id" is always picked before the "cachename", so if someone use "name" for
 a "cachename" value they get a error, because the alias "name" is no
longer avaibale, because the argument id is already taken, so he gets a
proper error.

Micha

2013/1/23 Igal notifications@github.com

> Are you sure that you want to add alias "name" for ID? It can be confusing
> with cacheName which refers to the cache connection name.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/getrailo/railo/pull/123#issuecomment-12626604.

## 

/micha

Michael Offner CTO Railo Technologies GmbH

**Pull request closed without merging**
