### PR TITLE
solved ticket https://issues.jboss.org/browse/RAILO-2931

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
You do not check if count is bigger than 0.
What happen when count is bigger than the amount of elements, there is no test case for this.

**Comment by igal-getrailo** [comment]
updated per your comments.  new impl works fine when count is larger than ListLen().

**Comment by micstriit** [comment]
Still missing dealing with count <=1

**Comment by igal-getrailo** [comment]
It's there
https://github.com/igal-getrailo/railo/commit/09ad0e65c141092c70127d7063611ee0717f2745#diff-423c0ff14f3fdd206f10255fb6d6c11eR29

**Pull request merged**
