### PR TITLE
update javasysmon to 0.3.4

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by micstriit** [comment]
Sorry but no, i had big trouble in past with fragmentation of Railo releases, we updated jars between 1 and 2 all the time was has resulting in problems we could not reproduce anymore, because we had a different  enviroments. 
"I expect your test cases to tell if any issues are created due to such update but I didn't find any" 
updating jars is always a mess, believe me, you have more believe in my testcases than i have, see the mess we had just some time ago with updating a jdbc driver and jdbc should be secure to update!

**Comment by micstriit** [comment]
you can do this for develop branch

**Comment by igal-getrailo** [comment]
ok.  will do for Develop.

**Comment by micstriit** [comment]
we can do this with develop branch

**Pull request closed without merging**
