### PR TITLE
added .cfs extension for processing cfscript without tag

### PR DESCRIPTION
**Pull request by igal-getrailo**
instead of pull #312

### CODE REVIEW

**Comment by micstriit** [comment]
Pleas do not use "loadFromSystem" to get the script tag, even this method has a cache, then name indicates otherwise and the behavior can change in the future. the method is only used once in the complete code, i would like to keep this that way.
get the tag the following way:
tlds = ((ConfigImpl)pc.getConfig()).getTLDs();

**Comment by micstriit** [comment]
for the .cfc template the <cfscript> is optional, i would like to have it the same way for .cfs

**Comment by igal-getrailo** [comment]
making the &lt;script&gt; tag optional adds unneeded overhead IMO, and unless we agree that it must be the first tag (i.e. no cfml comments before it) it will result in code similar to my first impl at #312 which you rejected for that very same reason.

all text editors that can handle .cfc can show script code highlighting without the script tag.

**Comment by igal-getrailo** [comment]
loadFromSystem is used in 
https://github.com/igal-getrailo/railo/blob/4.1/railo-java/railo-core/src/railo/transformer/cfml/tag/CFMLTransformer.java#L221

should I change it there too?  it is called from the transform() method

**Comment by igal-getrailo** [comment]
please see updates per your comments:
https://github.com/getrailo/railo/pull/341/files#diff-176b22002c1cf6953cae2058bfb7edc0R137

**Comment by micstriit** [comment]
we will add to develop branch

**Pull request closed without merging**
