### PR TITLE
updated apache commons email from 1.2 to 1.3.1; release notes:

### PR DESCRIPTION
**Pull request by igal-getrailo**
## CHANGES FROM 1.3:

== Compatibility ==
- Java 5 or later is required (unchanged since 1.3).

== Fixed Bugs ==
- DataSourceClassPathResolver will now correctly set the DataSource name for resolved
  resources. Additionally, it is now possible to set the name for a ByteArrayDataSource.
  Issue: EMAIL-125. Thanks to Jean-Marc.
- Header values are not folded twice anymore. The actual encoding and folding is
  now only performed in Email.buildMimeMessage().
  Issue: EMAIL-124. Thanks to Stefan Schueffler.
## CHANGES FROM 1.2:

== Compatibility ==
- Java 5 or later is now required.

== New Features ==
- Added new methods addTo(String[]), addCc(String[]) and addBcc(String[]) to Email.
  Issue: EMAIL-114. Thanks to Gokul Nanthakumar C.
- HtmlmageEmail should support class path resources
  Issue: EMAIL-108. Thanks to Elisabeth Kasimir, Alexander Kasimir.
- Added a MultiPartEmail.attach(File) method since attaching a file is a simple and common.
- Added MimeMessageParser and MimeMessageUtils.

== Fixed Bugs ==
- Use the provided Content-ID in HtmlEmail#embed(File, String) instead of creating
  a random one. The used and returned Content-ID will be URL encoded (see RFC 2392).
  Issue: EMAIL-101. Thanks to Andrew Starodub.
- Upgraded source and binary compatibility to JDK 1.5. Additionally the public/protected
  methods and fields have been properly generified.
  Issue: EMAIL-122. Thanks to sebb.
- Do not set the personal name of an address to the email address unless it is
  explicitly specified (affects TO, CC, BCC and FROM addresses).
  Issue: EMAIL-103. Thanks to David Rees.
- Removed emulation support for nested exceptions in EmailException.
  Issue: EMAIL-117. Thanks to sebb.
- Prevent external modification of internal array in DataSourceCompositeResolver.
  Issue: EMAIL-116. Thanks to sebb.
- Close temporary input stream in MultiPartEmail#attach(DataSource, String, String)
  to prevent locking of file resources on windows systems.
  Issue: EMAIL-120. Thanks to Mike Bell.
- The patch actually broke sending emails over a secured connection - disabled the
  "MAIL_SMTP_SSL_CHECKSERVERIDENTITY" and "MAIL_SMTP_SSL_ENABLE" activation. Tested
  the functionality using GMail, GMX and Office365 so the code is at least working for
  a couple of existing SMTP servers. Also added 'sslCheckServerIdentity' including
  setter and getter. Also added a chapter regarding "Security" to the user manual.
  Issue: EMAIL-105. Thanks to Siegfried Goeschl.
- Maven Site fails with error in Checkstyle configuration.
  Issue: EMAIL-113. Thanks to Peter Kofler.
- DataSourceFileResolverTest fails under IBM JDK 1.4 and 1.6 running on Windows.
  Issue: EMAIL-112. Thanks to Peter Kofler.
- Update the current trunk to be binary compatible with the commons-email-1.2 release.
  Issue: EMAIL-111. Thanks to Florian Pirchner.
- Added unit test to ensure that parsing the broken mime message does not cause an OutOfMemoryException.
  Issue: EMAIL-110. Thanks to Thomas Pummer.
- Added mime.types to META-INF - the definition is actually found in activation.jar
  but did not work.  Issue: EMAIL-107. Thanks to Claus Polanka, Michael Jakl.
- STARTTLS can be used even without authenticator.
  Issue: EMAIL-106. Thanks to Bruno Harbulot.
- Clarified the meaning of setTLS() which actually sends a "STARTTLS" command from the
  client to the SMTP server. Please note that some "protected" variables were renamed
  which could break existing code.
  Issue: EMAIL-105. Thanks to Bruno Harbulot.
- Fixed HtmlEmail embed toLowerCase bug with Turkish locale.
  Issue: EMAIL-102. Thanks to Okan Özeren.
- Specified Content-ID is now used when embedding a File object in an HtmlEmail.
  Issue: EMAIL-101. Thanks to Andrew Starodub.
- Throwing an IllegalStateException when setting mail session properties for an already
  created mail session because the settings would be ignored. Please note that this
  change could potentially break existing (but invalid) code.  Issue: EMAIL-96.
- Encoding and folding of headers is now done by commons-email.
  Issue: EMAIL-98. Thanks to Mario Daepp.
- The default connection timeout is set to a reasonable default value of 60 seconds.
  Issue: EMAIL-100. Thanks to David Parks.
- Moving the various constants from 'EMail' to 'EmailConstants'
- All setters are returning "this" to simplify building an email.
  Issue: EMAIL-76. Thanks to Yu Kobayashi.
- Adding ImageHtmlEmail to create HTML emails with embedded images either
  downloaded from HTTP or from the local file system.
  Issue: EMAIL-92. Thanks to Dominik Stadler.
- Calling buildMimeMessage() before invoking send() caused
  duplicated mime parts for HtmlEmail. The implementation now enforces
  that an email can be only used once and throw an exception when
  multiple invocations of buildMimeMessage() are detected.
  Issue: EMAIL-95.
- Incorrect SMTP Port number shown in error message when an email fails
  to send due to a blocked port and SSL is used.
  Issue: EMAIL-91. Thanks to Kevin Lester.

### CODE REVIEW

**Comment by micstriit** [comment]
see comment for other jar update

**Comment by igal-getrailo** [comment]
commons-email 1.2 has some bugs that prevent certain functionality from working properly.  on my servers I've been using 1.2.5 with Railo for the past two years.  1.3.1 further fixes bugs.  I can update it to Develop branch if that's what you want but IMO these updates are long past due.

**Comment by igal-getrailo** [comment]
look at the list of bug fixes above (on the github discussion)

**Comment by micstriit** [comment]
we can do this with develop branch

**Pull request closed without merging**
