### PR TITLE
Default extends attribute to true

### PR DESCRIPTION
**Pull request by bdw429s**
Default extends attribute to true to match ACF documented behavior

### CODE REVIEW

**Comment by bdw429s** [comment]
Related ticket: https://issues.jboss.org/browse/RAILO-2266

**Comment by andreacfm** [comment]
I am not sure if this makes sense. Setting this to true by default means more job will be done even if you do not require it.
Does this makes any sense?

**Comment by bdw429s** [comment]
Yes, that does make sense but it seems very odd to me that object inheritance would not be obeyed by default.  When I extend a regular CFC I expect inherited methods to be there and be usable without me needing to tell the compiler, "no kidding, I actually want these."   Why would I bother extending a base class if I didn't want to use inheritance?  It makes no sense.  

When my proxies extend a base proxy, I shouldn't need to tell the engine to actual pay attention to the inheritance chain-- that should be the default behavior.  Breaking the rules of inheritance should be something I have to explicitly configure.  GetMetaData() already pulls the inheritance chain so I can't imagine the few nanoseconds spend looping over another array should play any bearing on this functionality.

Also, ACF inherits remote methods by default (as I would expect).  I think it's cool that Railo gives me the choice to inherit methods (though I'm not sure when I wouldn't want to) but the default behavior of Railo is such that code running on ACF errors when ported to Railo which is also a compatibility issue.

Thanks!

~Brad

**Comment by andreacfm** [comment]
Looks reasonable.
I will test and merge asap.

Andrea

**Comment by bdw429s** [comment]
Thank you.  Please note, I entered ticket RAILO-2266 for the changes as well.

**Comment by andreacfm** [comment]
Merged into 4.0 branch for release in next patch

**Pull request closed without merging**
