### PR TITLE
created new scripts to generate admin resources

### PR DESCRIPTION
**Pull request by igal-getrailo**
removed HTTPCaching.cfc and dependency on it

 and moved sources from folder factory to resourcessrc.  also updated jquery to v1.8.3

static resources can now be generated by placing the static files in /resourcessrc/img, resourcessrc/css, and resourcessrc/js, and then calling /resourcessrc/generateall.cfm

### CODE REVIEW

**Comment by micstriit** [comment]
I have Not Look into it yet, but there is still a Problem with httpcaching in Railo 4.0, it produce Ettag, based on the file.lastmodified, there is no need for that, because all this files are in the .ra and the .ra only change with a new version, so this ettag should be produced on version number. We should first solve the problem in 4.0, otherwise it gets a pain in the ass to merge branch 4.0 into develop.

**Comment by igal-getrailo** [comment]
I removed the dateModified check here.  

there are two types of files: images and text (js/css).  in either case the script I wrote reads the contents of the source file (if it's an image converts it to base64) -- and then put that string in a <cfsavecontent variable="content">...</cfsavecontent>

the etag that I'm producing is a hash( content ) so it's based on the content itself regardless of the timestamp or version.

I will look into the 4.0 branch.

**Comment by micstriit** [comment]
i think hash(filename&"-"&server.railo.version) should already do the trick

**Comment by igal-getrailo** [comment]
True, but I already have the content variable there.  It's not like I added
it just for the hash.

Also those files are not likely to change with a minor version update but
one request per upgrade doesn't make any difference.

I can change it like you said if you still prefer that.

## 

typos, misspels, and other weird words brought to you courtesy of my mobile
device and its auto-(in)correct feature.

**Comment by micstriit** [comment]
my only concern with this is performance.
how long it takes to generate the hash for a file in average size?

Micha

2013/1/18 Igal notifications@github.com

> True, but I already have the content variable there. It's not like I added
> it just for the hash.
> 
> Also those files are not likely to change with a minor version update but
> one request per upgrade doesn't make any difference.
> 
> I can change it like you said if you still prefer that.
> 
> ## 
> 
> typos, misspels, and other weird words brought to you courtesy of my
> mobile
> device and its auto-(in)correct feature.
> On Jan 18, 2013 1:03 AM, "Michael Offner" notifications@github.com
> wrote:
> 
> > i think hash(filename&"-"&server.railo.version) should already do the
> > trick
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/getrailo/railo/pull/114#issuecomment-12413578>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/getrailo/railo/pull/114#issuecomment-12414336.

## 

/micha

Michael Offner CTO Railo Technologies GmbH

**Comment by igal-getrailo** [comment]
I doubt that it makes much difference but I will test and let you know.

## 

typos, misspels, and other weird words brought to you courtesy of my mobile
device and its auto-(in)correct feature.

**Comment by micstriit** [comment]
what i see in the current version of Railo 4.0 , that the image loading of
the admin takes more time than in Railo 3.
specially the first request takes forever.

Micha

2013/1/18 Igal notifications@github.com

> I doubt that it makes much difference but I will test and let you know.
> 
> ## 
> 
> typos, misspels, and other weird words brought to you courtesy of my
> mobile
> device and its auto-(in)correct feature.
> On Jan 18, 2013 1:27 AM, "Michael Offner" notifications@github.com
> wrote:
> 
> > my only concern with this is performance.
> > how long it takes to generate the hash for a file in average size?
> > 
> > Micha
> > 
> > 2013/1/18 Igal notifications@github.com
> > 
> > > True, but I already have the content variable there. It's not like I
> > > added
> > > it just for the hash.
> > > 
> > > Also those files are not likely to change with a minor version update
> > > but
> > > one request per upgrade doesn't make any difference.
> > > 
> > > I can change it like you said if you still prefer that.
> > > 
> > > ## 
> > > 
> > > typos, misspels, and other weird words brought to you courtesy of my
> > > mobile
> > > device and its auto-(in)correct feature.
> > > On Jan 18, 2013 1:03 AM, "Michael Offner" notifications@github.com
> > > wrote:
> > > 
> > > > i think hash(filename&"-"&server.railo.version) should already do
> > > > the
> > > > trick
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/getrailo/railo/pull/114#issuecomment-12413578>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/getrailo/railo/pull/114#issuecomment-12414336>.
> > 
> > ## 
> > 
> > /micha
> > 
> > Michael Offner CTO Railo Technologies GmbH
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/getrailo/railo/pull/114#issuecomment-12414497>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/getrailo/railo/pull/114#issuecomment-12414644.

## 

/micha

Michael Offner CTO Railo Technologies GmbH

**Comment by igal-getrailo** [comment]
I will check.

Also there are a few more small images (arrows etc) that I can add to the
new sprite so that will reduce http requests, but that's in 4.1

## 

typos, misspels, and other weird words brought to you courtesy of my mobile
device and its auto-(in)correct feature.

**Comment by igal-getrailo** [comment]
FYI:  hash() of the admin-sprite.png takes an average of 0.230ms while hash of ( CGI.SCRIPT_NAME & "-" & server.railo.version ) takes an average of 0.003ms in the same environment.

admin-sprite.png is the largest of the resources and is 15 - 20 times larger than most of the others.

but even though it's only 1/4 of a millisecond you convinced me of going with SCRIPT_NAME + Version

**Comment by igal-getrailo** [comment]
I'm sorry, I got confused by this whole discussion.  the way I wrote it the ETag is calculated when the resource file is generated and is coded with the file, so the 0.23 millisecond takes place when the file is created (only when we change the UI in the admin), and not at runtime when the resources are requested.

this really is not an issue.

**Comment by igal-getrailo** [comment]
I will improve this and open a new request when ready

**Pull request closed without merging**
