### PR TITLE
two single quotes inside a string value of a cfscript 'Query' function adds a space between them... 

### PR DESCRIPTION
**Pull request by clitnak**
the code:
var a =new Query("select name from users where last_name = 'o''brian'");
   a.execute();

results in the following query being executed against the database (notice the space between the single quotes):
select name from users where last_name = 'o' 'brian'

As you know, two single quotes inside a literal string is escaped to one single quote in all the RDBMS's I know of.

I tested this the best I can. hopefully this is good enough to be accepted.

### CODE REVIEW

**Comment by igal-getrailo** [comment]
hey Colby -- I was working on this right now as well and you just beat me to the pull request ;)

in line 141: please prefix the index in the cfloop with "Local." so that it reads index="Local.item".  

I believe that this should fix the bug reported in StackOverflow as well.

thank you.

**Comment by igal-getrailo** [comment]
also, as a general rule -- every bug should have a ticket in the JIRA.  can you open a ticket for that and reference this pull request?  thanks.

**Comment by clitnak** [comment]
https://issues.jboss.org/browse/RAILO-2259

I scoped the 'item' var. In my defense, it wasn't scoped before I touched. I should have noticed that though since I was there.

**Comment by igal-getrailo** [comment]
something got messed up here.  now there's a bunch of files in the patch.  this patch should only have Base.cfc modified.

I know that it wasn't scoped before you touched it ;)  I just noticed it when I was testing.

also, in Railo you don't need to scope it in all the subsequent references.  once you scope it in the first reference (line 141) you don't need to scope it in the others as the Local scope is the first once checked.  that's the reason I wrote to change it in line 141 ;)

**Comment by clitnak** [comment]
I am not sure what happened with all these files. I am closing this pull... go ahead and redo your pull Igal.

Re: scoping subsequent references... there is nothing wrong with being explicit is there? I always scope everything, it makes it easier to read, protects against confusion with variables scoped vars with the same name. I have yet to find a good reason not scope all uses.

**Comment by igal-getrailo** [comment]
OK, I'll open a pull for this.  Thank you for your work and input.

As for the explicit scoping, you're right, nothing wrong with it, but it
adds clutter and make the code less readable IMO.

## 

typos, misspels, and other weird words brought to you courtesy of my mobile
device and its auto-(in)correct feature.

**Comment by igal-getrailo** [comment]
p.s.  --  there can not be confusion between var scoped variables and Local scoped variables as they share the same scope.  for example:

```
function getValue1() {

    var x = 10;
    Local.x = 20;
    return x;   // returns 20
}

function getValue2() {

    Local.x = 20;
    var x = 10;
    return Local.x; // returns 10
}
```

**Pull request closed without merging**
