### PR TITLE
added capitalize() method to StringUtil and overloaded UCFirst

### PR DESCRIPTION
**Pull request by igal-getrailo**
added UCFirst( string, boolean )

### CODE REVIEW

**Comment by micstriit** [comment]
i have changed the implementation a little bit
https://github.com/getrailo/railo/commit/8ed7ee141132eccd07b185ce67a87ada545f292e

main changes are:
- to check if a string is "empty" always use one of the StringUtil.isEmpty() methods
- the usage of native arrays is always preferred (char[] instead of List<Character>), when the size of the array does not change, because it is faster

tnx micha

**Comment by igal-getrailo** [comment]
ok, but all that StringUtil.isEmpty( str ) is doing is pretty much the same thing:

```
public static boolean isEmpty(String str) {
    return str==null || str.length()==0;
}
```

so inline-ing that code saves a method call, no?

also, maybe isEmpty( String str ) should use str.isEmpty() instead of str.length()==0 ?  I'm not sure if that even makes a difference in the bytecode.  just a thought.

**Comment by micstriit** [comment]
i use the isEmpty method for 2 reasons all over Railo.
i prefer to have consistent code, i use this isEmpty method long before
there was a isEmpty method in the String class
and i hate to have code everywhere looking like this  if(str==null ||
str.length()==0).

but for me the main reason to use this method is to make sure we always
have a null check, so i also use the isEmpty method even i'm mostly sure
the value is not null.
so instead of if(str.isEmpty()) i always to if(StringUtil.isEmpty(str)).

from performance standpoint this makes no difference (i have tested this a
long time ago), then most java compiler (or all) optimize this kind of
method calls and do inlining the called code in this case, the rule is:
for static method call that do not set variables and the code is short,
copy the code to the caller instead of call the method.
i would love to do things like this in Railo as well, but Railo is a
dynamic language and because of that it is not possible, means Railo
defines at runtime which method to call, not at compile time.

about the performance between String.length()==0 and String.isEmpty(), this
is the code from the String class

public int length() {
   return count;
}
public boolean isEmpty() {
   return count == 0;
}

so it makes no difference in performance, in one case we do
the comparison to 0 outside the method in the other case inside the method.
of course we can change the Stringutil.isEmpty method, this method was
written when we still have supported Java 1.4 and Java 1.4 had no support
for String.isEmpty().

2013/2/18 Igal notifications@github.com

> ok, but all that StringUtil.isEmpty( str ) is doing is pretty much the
> same thing:
> 
> public static boolean isEmpty(String str) {
>     return str==null || str.length()==0;
> }
> 
> so inline-ing that code saves a method call, no?
> 
> also, maybe isEmpty( String str ) should use str.isEmpty() instead of
> str.length()==0 ? I'm not sure if that even makes a difference in the
> bytecode. just a thought.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/getrailo/railo/pull/131#issuecomment-13709959.

## 

/micha

Michael Offner CTO Railo Technologies GmbH

**Comment by igal-getrailo** [comment]
thanks for the detailed explanation.  I will read it more carefully next.

the reason I used List<Character> was because I wanted to take advantage of List.contains( c ) method.  I see now that you have a similar method for the array.

I also considered using a String, and calling String's indexOf( c ) instead.  I'm not sure what's faster/better.

**Pull request merged**
