### PR TITLE
Fix so CFAjaxProxy will not error when CFC points to a file with no functions.

### PR DESCRIPTION
**Pull request by bdw429s**
...

### CODE REVIEW

**Comment by bdw429s** [comment]
Related ticket: https://issues.jboss.org/browse/RAILO-2265

**Comment by bdw429s** [comment]
Is there anything I can provide to help get this merged?

**Comment by andreacfm** [comment]
Please send pull request on this repo to master branch  [RailoAjax](https://github.com/andreacfm/railoajax). It is much more easier for me to merge from there.

**Comment by bdw429s** [comment]
To be clear, you want me to send my pull request to your personal repo?  Should I send future Railo pull requests to your repo, or only this one?  Sorry, it just seems a little odd.

**Comment by igal-getrailo** [comment]
I believe (and Andrea -- please correct me if I'm wrong) that yes -- for the Ajax-related patches please submit the pull requests to Andrea's repo so that he can test it prior to pushing it to the Railo repo.

**Comment by bdw429s** [comment]
Ok, thanks.  It might be helpful to document that somewhere.  :)  I submitted this ajax-related pull request (https://github.com/getrailo/railo/pull/125) at the same time as this one to the main Railo repo and it was merged as-is.

**Comment by igal-getrailo** [comment]
most likely because that patch was minor and did not require much 
testing, but again, Andrea will know better why he chose to do things 
the way he did.

**Comment by bdw429s** [comment]
New pull request here: https://github.com/andreacfm/railoajax/pull/3

**Comment by andreacfm** [comment]
Brad.

This just makes easier for me to test before merging. 
Tests for ajax stuff are not integrated into railo test suite.
Nothing more that this.

Andrea

On May 5, 2013, at 10:21 PM, Brad Wood notifications@github.com wrote:

> New pull request here: andreacfm/railoajax#3
> 
> —
> Reply to this email directly or view it on GitHub.

Andrea Campolonghi
acampolonghi@gmail.com

**Pull request closed without merging**
