### PR TITLE
set cfid and cftoken cookies as httponly

### PR DESCRIPTION
**Pull request by igal-getrailo**

### CODE REVIEW

**Comment by jhfrench** [comment]
Can I take this to mean that cfid and cftoken will not be set on https servers? Therefor, session variables cannot be set on a https page that attempts to set the session variable(s) then uses cflocation?
See http://helpx.adobe.com/coldfusion/kb/missing-session-variables-using-cflocation.html

**Comment by igal-getrailo** [comment]
this added the flag "HttpOnly" and not the flag "Secure" -- it tells the browser not to allow JavaScript access to this cookie.  I don't see why it would affect anything on the server?

**Comment by jhfrench** [comment]
My understanding is that `cfid` and `cftoken` are the cookies that CFML uses to track a user's session. _If_ those cookies cannot be set on an https page, then sessions cannot be created/tracked on that page.

**Comment by igal-getrailo** [comment]
of course they are set on https requests.

**Pull request merged**
